---
title: "Second_tidytue"
author: "liujian"
date: "2019/6/5"
output: 
  html_document:
    keep_md: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Introduction 

**[Github](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-06-04)**

# Packages and browsing

```{r libraries}
library(tidyverse)
library(countrycode)
library(sp)
library(maps)
library(maptools)
library(leaflet)
ramen_ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-04/ramen_ratings.csv")

```
```{r glimpse}
glimpse(ramen_ratings)

sapply(ramen_ratings, function(x) length(unique(x)))

sapply(ramen_ratings, range, na.rm = T)

unique(ramen_ratings$country)[order(unique(ramen_ratings$country))]

```

# Clean the country name

```{r corretion}

update_coutry <- ramen_ratings %>% 
  mutate(country = recode(country,
                          "Phlippines" = "Philippines",
                          "Hong Kong" = "China",
                          "Taiwan" = "China",
                          "Holland" = "Netherlands",
                          "Dubai" = "United Arab Emirates",
                          "Sarawak" = "Malaysia"))

update_coutry %>% 
  filter(is.na(country))

unique(update_coutry$country)[order(unique(update_coutry$country))]


```


# An interactive map shows which country has the top number of reviews

**Probably indicates these countries have a large population that are living on instant ramen if there are high numbers of reviews.**

```{r leaflet}

#https://stackoverflow.com/questions/33041266/r-rworldmap-map-issue-and-leaflet-application
world <- map("world", fill=TRUE, plot=FALSE)
world_map <- map2SpatialPolygons(world, sub(":.*$", "", world$names))
world_map <- SpatialPolygonsDataFrame(world_map,
                                      data.frame(country=names(world_map), 
                                                 stringsAsFactors=FALSE), 
                                      FALSE)

cnt <- unique(update_coutry$country)

target <- subset(world_map, country %in% cnt)
# bins <- c(0, 1000, 1500, 2000, 2200, 2500, 2700, 3000, 3300)
# pal <- colorBin("viridis", domain = update_coutry$review_number, bins = bins)
# 
# leaflet(target) %>% 
#   addTiles() %>% 
#   addPolygons(fillColor = ~pal(update_coutry$review_number),
#               weight = 2,
#   
#   color = "white",
#   dashArray = "3",
#   fillOpacity = 0.7)
no_of_reviews <- update_coutry %>% 
  group_by(country) %>% 
  summarise(sum_review = sum(review_number, na.rm = T)) %>% 
  arrange(sum_review)

target@data <- target@data %>% 
  left_join(no_of_reviews)
pal <- colorBin("RdYlBu", domain = target$sum_review, bins = 5, reverse = TRUE)
leaf <- leaflet(target) %>% 
  addTiles() %>% 
  addPolygons(fillColor = ~pal(sum_review),
              weight = 2,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7) %>% 
  addLegend(pal = pal, values = ~sum_review, opacity = 0.7, title = NULL,
  position = "bottomleft")

library(htmlwidgets)
 library(htmltools)

 rr <- tags$div(
   HTML('<a> Number of reviews for Ramen rating in 38 countries</a>')
 ) 

leaf  %>%
   addTiles() %>%
   
   addControl(rr, position = "bottomright")
```

# The treemap to show the family member of the brand 

```{r the most popular}

library(treemap)

df_treemap <- update_coutry %>% 
  select(brand, variety) %>% 
  group_by(brand) %>%
  count() %>% 
  arrange(desc(n)) %>% 
  filter(n >10)
treemap(df_treemap, 
        index = "brand", 
        vSize = "n",
        vColor = "n", 
        type="value", 
        title = "The total number of product for each brand", 
        title.legend = "Number of products indication", 
        palette="Spectral",
        border.col=c("grey50"),             # Color of borders of groups, of subgroups, of subsubgroups ....
        border.lwds = "3", 
        bg.labels=c("transparent")
   
)
```

